name: Add Milestoned Issues to Board

on:
  issues: 
    types:
      - milestoned

jobs:
  add-to-sprint-board:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.FACELESS_TOKEN}}
          script: |
            console.log(context)

            // Get the repo projects (boards)
            const boardResps = await github.projects.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
            })
            const boards = boardResps.data
            console.log(boards)

            // Get the sprint board
            for (board of boards) {
              if (board.name == 'Sprint Board') {

                // Get the To do column
                const columnsResp = await github.projects.listColumns({
                  project_id: board.id
                })

                const columns = columnsResp.data

                for (column of columns) {
                  if (column.name == 'To do') {
                    await github.projects.createCard({
                      column_id: column.id,
                      content_id: context.payload.issue.number,
                      content_type: 'Issue'
                    })
                    break
                  }
                }
                break
              }
            }
