name: Block Invalid Tasks

on:
  project_card: 
    types:
      - moved

jobs:
  block-invalid-task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.FACELESS_TOKEN}}
          script: |
            // Get the issue from the context
            const issue_url = context.payload.project_card.content_url
            var path = require('path')
            const issue_number = path.basename(issue_url)

            const labels = await github.issues.listLabelsOnIssue({
              issue_number: issue_number,
              owner: context.repo.owner,
              repo: context.repo.repo
            })

            console.log(labels)
