name: Block Invalid Tasks

on:
  project_card: 
    types:
      - labeled

jobs:
  block-invalid-task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.FACELESS_TOKEN}}
          script: |
            console.log(context)
