name: Block Invalid Tasks

on:
  project_card: 
    types:
      - moved

jobs:
  block-invalid-task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.FACELESS_TOKEN}}
          script: |
            // Get the issue from the context
            const issue_url = context.payload.project_card.content_url
            const card_id = context.payload.project_card.id
            var path = require('path')
            const issue_number = path.basename(issue_url)

            const labelResp = await github.issues.listLabelsOnIssue({
              issue_number: issue_number,
              owner: context.repo.owner,
              repo: context.repo.repo
            })

            const labels = labelResp.data

            console.log(context)

            var labelNames = []
            for (label of labels) {
              labelNames.push(label.name)
            }

            if  (labelNames.includes('task') && labelNames.includes('invalid')) {
              const currentColumnId = context.payload.project_card.column_id
              const currentColumnResp = await github.projects.getColumn({
                column_id: currentColumnId
              })
              const changes = context.payload.changes
              const currentColumn = currentColumnResp.data
              if (currentColumn.name != 'To do') {
                // This is hacky, but let's assume that that the invalid tasks are only
                // ever moved from the `To do` column so changes.column_id.from
                // Will be the column to move it to
                console.log('Invalid task outside of To do') 
                await github.projects.moveCard({
                  card_id: card_id,
                  position: 'top',
                  column_id: changes.column_id.from
                })
              }
            }
