name: Create Draft PR

on:
  push:
    branches:
      - 'issue-*'

jobs:
  create-draft-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.FACELESS_TOKEN}}
          script: |
            var path = require('path')
            const branch = path.basename('${{github.ref}}')
            const pullsListResp = await github.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              head: `${context.repo.owner}:${branch}`
            })
            const pullsList = pullsListResp.data
            if (!pullsList.length) {
              await github.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: 'Test Draft PR',
                body: 'Closes some issue',
                head: branch,
                base: 'master',
                draft: true
              })
            }
