on:
  issues: {types: labeled}

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.FACELESS_TOKEN}}
          script: |
            const labelsResp = await github.issues.listLabelsOnIssue({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo
            })


            const labels = labelsResp.data

            const labelNames = []
            const labelDescs = []

            for (label of labels) {
              console.log(label)
              labelNames.push(label.name)
              labelDescs.push(label.description)
            }

            if  (labelNames.includes('task')) {
              if (!labelDescs.includes('Task Size Label')) {
                await github.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: 'Add a time estimate you goon!'
                })
              }
            }
