on:
  issues: {types: labeled}

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.FACELESS_TOKEN}}
          script: |
            const labels = github.issues.listLabelsOnIssue({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo
            })

            const labelNames = []
            const labelDescs = []

            for (label of labels) {
              labelNames.push(label.name)
              labelDescs.push(label.description)
            }
